### ISSUE TITLE
Whitepaper

### ISSUE THREAD

**Issue by jacksonloper** [mukamel-lab/SingleCellFusion#1]
Hi all, Jackson Loper here from the Paninski Lab at Columbia University.  I was wondering what the latest and greatest whitepaper for this repo is?  I didn’t find anything on arxiv/biorxiv, but maybe I missed it.   

It would be great to have a link to something that lays out the math in a latex.  Cheers.

**Comment by wayneidoyle** [comment]
Hi. Thanks for the interest! We are currently working on a preprint, but to get you something a little bit sooner we are currently updating the documentation on the repository which will include the math behind SingleCellFusion. We hope to have that out in the next week or two.

**Comment by wayneidoyle** [comment]
Hi, we are still working on a white paper but in the interim you can take a look at the descriptions that we have provided for the integration at: https://github.com/mukamel-lab/SingleCellFusion/blob/master/docs/scf_description.rst. You can also get to it by scrolling down  to "Tutorials and FAQs" on the main page of the repo and clicking the link for more information on how SingleCellFusion works. Hope that helps!
